name: ezze_stores
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.12.4
  provider: ^6.1.5+1
  mobile_scanner: ^7.2.0
  flutter_dotenv: ^6.0.1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21